#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Colors
export TERM=xterm
RED=$(tput -T xterm setaf 1)
GREEN=$(tput -T xterm setaf 2)
NC=$(tput -T xterm sgr0)

# Actors
CC="ilihub"
CDR="gitgod"

echo ""
echo "${RED}${CDR}${NC}: Commit completed."
echo "${GREEN}${CC}${NC}: Roger. We confirm commit completed."

echo ""
echo "${RED}${CDR}${NC}: Good deal."
echo "${RED}${CDR}${NC}: Shutdown."
echo "${GREEN}${CC}${NC}: Roger. Shutdown."
echo ""
