name: Sponsors Auto PR

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Update Sponsors Section]
    branches: [master]
    types:
      - completed

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  auto_pr:
    uses: ilihub/.github/.github/workflows/sponsors-auto-pr.yml@master
