name: Sponsors Auto PR

on:
  workflow_dispatch:
  push:
    branches: ["readme-update-sponsors-section"]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  auto_pr:
    uses: ilihub/.github/.github/workflows/sponsors-auto-pr.yml@master
