name: Update Sponsors Section

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    types: [opened, synchronize]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  update_sponsors:
    uses: ilihub/.github/.github/workflows/sponsors.yml@master
